version: 2

sources:
  - name: klaytn_silver
    database: klaytn
    schema: silver
    tables:
      - name: labels
      - name: blocks
      - name: logs
      - name: receipts
      - name: traces
      - name: transactions
      
  - name: github_actions
    database: kaia
    schema: github_actions
    tables:
      - name: workflows
  - name: silver_crosschain
    database: "{{ 'crosschain' if target.database == 'KAIA' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis