version: 2

sources:
  - name: klaytn_silver
    database: klaytn
    schema: silver
    tables:
      - name: labels
      - name: blocks
      - name: logs
      - name: receipts
      - name: traces
      - name: transactions
      
  - name: github_actions
    database: kaia_dev
    schema: github_actions
    tables:
      - name: workflows
  - name: silver_crosschain
    database: "{{ 'crosschain' if target.database == 'KAIA' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis

  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "  KLAYTN_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "KLAYTN" }}
    tables:
      - name: contract_abis
  - name: kaia_silver
    database: kaia_dev
    schema: silver
    tables:
      - name: verified_abis
  - name: kaia_bronze_api
    database: kaia_dev
    schema: bronze_api
    tables:
      - name: contract_abis